services:
  - type: web
    name: talktime
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
